import gameJunkeeArr from './images/gameJunkee';
import muvdArr from './images/muvd';
import quizArr from './images/quiz';
import techsterBlogArr from './images/techsterBlog';
import textEditorArr from './images/textEditor';
import weatherDashboardArr from './images/weatherDashboard';


export const ApplicationData = [
    { id: 1, applicationTitle: "Game Junkee", mainPhoto: "../assets/gameJunkeePhotos/gamejunkee1.png", description: "With this project we wanted to create an application where users could post about games they love and other users could offer comments about the game and include recommendations about other games the original poster might enjoy.", applicationImage: gameJunkeeArr, applicationLink: "https://gamejunkee.herokuapp.com/", github: "https://github.com/Project-2-BJMS/GameJunkee" },
    { id: 2, applicationTitle: "Muvd", mainPhoto: "../assets/muvdPhotos/muvd1.png", description: "Muvd is an application that allows users to search for movies, or suggests movies based on the user's mood. It then shows some basic information about the movie from The Movie Database, and if available, provides a link to a review of the movie from the New York Times.", applicationImage: muvdArr, applicationLink: "https://coding-p1-g1.github.io/muvd/", github: "https://github.com/coding-p1-g1/muvd" },
    { id: 3, applicationTitle: "Tech Blog", mainPhoto: "../assets/techsterBlogPhotos/techsterblog1.png", description: "Tech-Blog site where users can be apart of a community and share interests or discuss new technology.", applicationImage: techsterBlogArr, applicationLink: "https://techsterblog.herokuapp.com/", github: "https://github.com/Blehjo/tech-blog" },
    { id: 4, applicationTitle: "Progressive Web Application", mainPhoto: "../assets/textEditorPhotos/texteditor1.png", description: "Website that I refactored with MERN stack. Allows the user to search for books and save it to his/her/their collection.", applicationImage: textEditorArr, applicationLink: "https://online-offline-editor.herokuapp.com/", github: "https://www.github.com/Blehjo/pwa" },
    { id: 5, applicationTitle: "Weather Dashboard", mainPhoto: "../assets/weatherDashboardPhotos/weatherdashboard.png", description: "Weather dashboard where users can search for cities and get the cities current weather and five-day forecast. The cities are also saved to local storage, so the user can access past searches.", applicationImage: weatherDashboardArr, applicationLink: "https://blehjo.github.io/weather-dashboard/", github: "https://github.com/Blehjo/weather-dashboard" },
    { id: 6, applicationTitle: "Quiz", mainPhoto: "../assets/quizPhotos/quiz1.png", description: "Squiz Game. Application that tests a user's ability to work under pressure. This site is one page and the user can play a game and keep track of his/her/their scores.", applicationImage: quizArr, applicationLink: "https://blehjo.github.io/quiz/", github: "https://github.com/Blehjo/quiz/" },
    { id: 7, applicationTitle: "Polari", mainPhoto: "../assets/polariPhotos/polari1.png", description: "Polari is a dating website catered to the LGBTQ community with an emphasis to educate users of their attachment styles", applicationImage: "polariArr", applicationLink: "https://polari-attachments.herokuapp.com/", github: "https://github.com/polari-2022" },
]